// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/match.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRequest) Reset() {
	*x = MatchRequest{}
	mi := &file_proto_match_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRequest) ProtoMessage() {}

func (x *MatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRequest.ProtoReflect.Descriptor instead.
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_match_proto_rawDescGZIP(), []int{0}
}

func (x *MatchRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type CreateMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	HomeTeam      string                 `protobuf:"bytes,2,opt,name=home_team,json=homeTeam,proto3" json:"home_team,omitempty"`
	AwayTeam      string                 `protobuf:"bytes,3,opt,name=away_team,json=awayTeam,proto3" json:"away_team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMatchRequest) Reset() {
	*x = CreateMatchRequest{}
	mi := &file_proto_match_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMatchRequest) ProtoMessage() {}

func (x *CreateMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMatchRequest.ProtoReflect.Descriptor instead.
func (*CreateMatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_match_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMatchRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *CreateMatchRequest) GetHomeTeam() string {
	if x != nil {
		return x.HomeTeam
	}
	return ""
}

func (x *CreateMatchRequest) GetAwayTeam() string {
	if x != nil {
		return x.AwayTeam
	}
	return ""
}

type MatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	HomeScore     int32                  `protobuf:"varint,3,opt,name=home_score,json=homeScore,proto3" json:"home_score,omitempty"`
	AwayScore     int32                  `protobuf:"varint,4,opt,name=away_score,json=awayScore,proto3" json:"away_score,omitempty"`
	LastEvent     string                 `protobuf:"bytes,5,opt,name=last_event,json=lastEvent,proto3" json:"last_event,omitempty"`
	Possession    int32                  `protobuf:"varint,6,opt,name=possession,proto3" json:"possession,omitempty"`
	Shots         int32                  `protobuf:"varint,7,opt,name=shots,proto3" json:"shots,omitempty"`
	Fouls         int32                  `protobuf:"varint,8,opt,name=fouls,proto3" json:"fouls,omitempty"`
	Cards         []string               `protobuf:"bytes,9,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResponse) Reset() {
	*x = MatchResponse{}
	mi := &file_proto_match_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResponse) ProtoMessage() {}

func (x *MatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResponse.ProtoReflect.Descriptor instead.
func (*MatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_match_proto_rawDescGZIP(), []int{2}
}

func (x *MatchResponse) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MatchResponse) GetHomeScore() int32 {
	if x != nil {
		return x.HomeScore
	}
	return 0
}

func (x *MatchResponse) GetAwayScore() int32 {
	if x != nil {
		return x.AwayScore
	}
	return 0
}

func (x *MatchResponse) GetLastEvent() string {
	if x != nil {
		return x.LastEvent
	}
	return ""
}

func (x *MatchResponse) GetPossession() int32 {
	if x != nil {
		return x.Possession
	}
	return 0
}

func (x *MatchResponse) GetShots() int32 {
	if x != nil {
		return x.Shots
	}
	return 0
}

func (x *MatchResponse) GetFouls() int32 {
	if x != nil {
		return x.Fouls
	}
	return 0
}

func (x *MatchResponse) GetCards() []string {
	if x != nil {
		return x.Cards
	}
	return nil
}

var File_proto_match_proto protoreflect.FileDescriptor

const file_proto_match_proto_rawDesc = "" +
	"\n" +
	"\x11proto/match.proto\x12\x05match\")\n" +
	"\fMatchRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\"i\n" +
	"\x12CreateMatchRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1b\n" +
	"\thome_team\x18\x02 \x01(\tR\bhomeTeam\x12\x1b\n" +
	"\taway_team\x18\x03 \x01(\tR\bawayTeam\"\x81\x02\n" +
	"\rMatchResponse\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"home_score\x18\x03 \x01(\x05R\thomeScore\x12\x1d\n" +
	"\n" +
	"away_score\x18\x04 \x01(\x05R\tawayScore\x12\x1d\n" +
	"\n" +
	"last_event\x18\x05 \x01(\tR\tlastEvent\x12\x1e\n" +
	"\n" +
	"possession\x18\x06 \x01(\x05R\n" +
	"possession\x12\x14\n" +
	"\x05shots\x18\a \x01(\x05R\x05shots\x12\x14\n" +
	"\x05fouls\x18\b \x01(\x05R\x05fouls\x12\x14\n" +
	"\x05cards\x18\t \x03(\tR\x05cards2\x8c\x01\n" +
	"\fMatchService\x12<\n" +
	"\x0fGetMatchUpdates\x12\x13.match.MatchRequest\x1a\x14.match.MatchResponse\x12>\n" +
	"\vCreateMatch\x12\x19.match.CreateMatchRequest\x1a\x14.match.MatchResponseB@Z>github.com/abaika-abay/live_sports_project/match-service/protob\x06proto3"

var (
	file_proto_match_proto_rawDescOnce sync.Once
	file_proto_match_proto_rawDescData []byte
)

func file_proto_match_proto_rawDescGZIP() []byte {
	file_proto_match_proto_rawDescOnce.Do(func() {
		file_proto_match_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_match_proto_rawDesc), len(file_proto_match_proto_rawDesc)))
	})
	return file_proto_match_proto_rawDescData
}

var file_proto_match_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_match_proto_goTypes = []any{
	(*MatchRequest)(nil),       // 0: match.MatchRequest
	(*CreateMatchRequest)(nil), // 1: match.CreateMatchRequest
	(*MatchResponse)(nil),      // 2: match.MatchResponse
}
var file_proto_match_proto_depIdxs = []int32{
	0, // 0: match.MatchService.GetMatchUpdates:input_type -> match.MatchRequest
	1, // 1: match.MatchService.CreateMatch:input_type -> match.CreateMatchRequest
	2, // 2: match.MatchService.GetMatchUpdates:output_type -> match.MatchResponse
	2, // 3: match.MatchService.CreateMatch:output_type -> match.MatchResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_match_proto_init() }
func file_proto_match_proto_init() {
	if File_proto_match_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_match_proto_rawDesc), len(file_proto_match_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_match_proto_goTypes,
		DependencyIndexes: file_proto_match_proto_depIdxs,
		MessageInfos:      file_proto_match_proto_msgTypes,
	}.Build()
	File_proto_match_proto = out.File
	file_proto_match_proto_goTypes = nil
	file_proto_match_proto_depIdxs = nil
}
